apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: tomcat
        image: saidamo/myweb:0.0.2
        ports:
          - containerPort: 8080
