apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels: 
    app: tomcat    
spec:
  type: NodePort 
  selector:
    app: tomcat
  ports: 
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - port: 443 
      targetPort: 8080
      protocol: TCP
      name: https
