apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels: 
    app: tomcat    
spec:
  type: ClusterIP
  selector:
    app: tomcat
  ports: 
    - name: http
      port: 80
      targetPort: 8080

